from yacs.config import CfgNode

_C = CfgNode()

_C.OPTIMIZATION = CfgNode()
_C.OPTIMIZATION.LEARNING_RATE = 0.1
_C.OPTIMIZATION.NUM_ITERATIONS = 1000
_C.OPTIMIZATION.LR_SCHEDULER_STEP = 10
_C.OPTIMIZATION.DELTA_POSE_LOSS = False

_C.OPTIMIZATION.WEIGHTS = CfgNode()
_C.OPTIMIZATION.WEIGHTS.HEIGHT = 1e3
_C.OPTIMIZATION.WEIGHTS.WAIST = 1e3
_C.OPTIMIZATION.WEIGHTS.HIP = 1e3
_C.OPTIMIZATION.WEIGHTS.JOINTS =  2
_C.OPTIMIZATION.WEIGHTS.SILHOUETTE = 1e-1
_C.OPTIMIZATION.WEIGHTS.NORM = 1e-2
_C.OPTIMIZATION.WEIGHTS.PRIOR_POSE = 2e4
_C.OPTIMIZATION.WEIGHTS.POSE_PRIOR = 1
_C.OPTIMIZATION.WEIGHTS.HEAD_FEET_PlANE = 5e3

_C.OPTIMIZATION.SWITCHES = CfgNode()
_C.OPTIMIZATION.SWITCHES.HEIGHT = True
_C.OPTIMIZATION.SWITCHES.WAIST = True
_C.OPTIMIZATION.SWITCHES.HIP = True
_C.OPTIMIZATION.SWITCHES.JOINTS = True
_C.OPTIMIZATION.SWITCHES.SILHOUETTE = True
_C.OPTIMIZATION.SWITCHES.NORM = True
_C.OPTIMIZATION.SWITCHES.PRIOR_POSE = True
_C.OPTIMIZATION.SWITCHES.HEAD_FEET_PLANE = True

def get_shape_optimization_cfg_defaults():
    return _C.clone()